### PR TITLE
Remove top-let computations

### PR DESCRIPTION
**Pull request by matijapretnar**
Having top-let definitions limited to expressions makes the system much simpler (especially down the road) but at a cost of a slight inconvenience for the user. In particular, some computations need to be defined as thunks (see modified examples). What are your thoughts on the simplification?

### CODE REVIEW

**Comment by zigaLuksic** [comment]
Does this let you *run* a program? For instance, if you write a game in **Eff**, can you make it so that whenever the file is evaluated, the game starts?

I figure you would have something like
```
let _ = run_game ()
```
as the last line of your file, but this is probably not allowed in the new approach.

**Comment by matijapretnar** [comment]
Yes, you can write

`run_game ()`

(you will likely need `;;` before it) - running top computations is still allowed, you just cannot bind resulting values.

**Comment by zigaLuksic** [comment]
I understand how this makes everything much simpler, but it feels like a hack to avoid correcting the desugaring step (and at this point it feels like half of our decisions are made to avoid fixing the desugarer). Would it perhaps help to have a toplevel (and only toplevel) distinction between `let` and `do`?

**Comment by matijapretnar** [comment]
The desugarer is not the problem. The problem is in tracking effect inference constraints since the rest of the program is essentially a never-ending continuation of a `do` introduced by binding a computation in a top `let`.

**Comment by zigaLuksic** [comment]
I would still argue that it is a bit of a problem with the sugared syntax but that is not really important for the issue at hand. 

Restricting toplevel `let` statements to values seems hacky (since it forces us to use `;;` which ideally should never be present in a file). Usually they are used just as function/handler definitions, but it also means we cant directly use random numbers or something of the sort.

**Comment by matijapretnar** [comment]
We're close to figuring out the solution for top-let computations in the new effect system, so let us keep them.

**Pull request closed without merging**
