### PR TITLE
Fixing the fork-bomb bug on rlwrap editing wrapper.

### PR DESCRIPTION
**Pull request by marcoonroad**

### CODE REVIEW

**Comment by marcoonroad** [comment]
eff-rlwrap-bug

**Comment by marcoonroad** [comment]
*This was the eff interpreter before the patch*

**Comment by marcoonroad** [comment]
Well, some old OCaml versions seem to not implement Array.mem (for example, v3.12). I can figure out a better replacement for that in such cases later.

**Comment by andrejbauer** [comment]
What problem are you solving here?

**Comment by marcoonroad** [comment]
Every time I use the Eff interpreter for the master branch (the stable branch is fine), it enters in an infinite loop without even show any message, for example, through the --help flag. I dunno if it is due my local version of rlwrap, but it is indeed related to such thing. Pardon me if I have not open a issue beforehand. I will try to update my version of rlwrap and test the eff interpreter on master branch against it.

**Comment by marcoonroad** [comment]
*Such infinite loop is due the recursive forking of rlwrap if my mind is still working in such night.*

**Comment by marcoonroad** [comment]
I have updated my local rlwrap (using the latest version, v0.43) and tested the eff interpreter (on this master branch, surely) with it, but the fork-bomb problem also occurs in that context.

**Comment by andrejbauer** [comment]
Instead of putting in that `if` statement, let us actually get to the root of the cause and make a fix where the fix needs to be made. The `if` you placed in is just something that masks the real problem.

When `eff` execs `rlwrap` it adds `--no-wrapper` as the *last* argument. Now, as far as I can see, this should prevent further execs because (I am *assuming* this) command-line arguments are parsed from left to right, so that last `--no-wrapper` *should* kill further execs. But apparently that's not what happens with your setup. Could you perform an experiment which tests whether the infinite loop is adding ever more `--no-wrapper` options (for instance by printing them out)?

A better solution would make sure that `--no-wrapper` always wins over any existing `--wrapper` option. Right not the "last" one wins.

**Comment by marcoonroad** [comment]
Thanks.

**Comment by marcoonroad** [comment]
eff-no-wrapper
eff-no-wrapper-diff

**Comment by marcoonroad** [comment]
It seems that the flag --no-wrapper has no effect at all (the same is valid for other flags, such as --help).

**Comment by andrejbauer** [comment]
Aha! So it's as if command-line parsing doesn't work. Interesting. So I take it you're printing `Sys.argv`? Which means that command-line parsing might be skipped somehow, let me stare at the code. Perhaps @matijapretnar knows if he changed anything lately.

**Comment by andrejbauer** [comment]
The reason `--help` isn't working is because in never gets a chance to do so. The first thing `eff` does is the command-line wrapper. What happens if in [this line](https://github.com/marcoonroad/eff/blob/428eec77750e8e3878ec8645dfb5a88986bc416b/src/eff.ml#L33) you change

    Arg.Unit (fun () -> wrapper := None)

to

    Arg.Unit (fun () -> print_endline "WE ARE HERE!" ; wrapper := None)

Do you see it print anything? This would confirm that `--no-wrapper` actually got parsed. I suspect it's not getting parsed.

**Comment by marcoonroad** [comment]
The result for the change that you propose is (using the unstaged changes here):

        λ(bash). ./eff
        ./eff
 

        ./eff
        --no-wrapper

 
        WE ARE HERE
        ./eff
        --no-wrapper
        --no-wrapper

 
        WE ARE HERE
        WE ARE HERE
        ./eff
        --no-wrapper
        --no-wrapper
        --no-wrapper

 
        WE ARE HERE
        WE ARE HERE
        WE ARE HERE
        ./eff
        --no-wrapper
        --no-wrapper
        --no-wrapper
        --no-wrapper

I can figure out the real source of problem looking with care the source code. By now, this PR can be open until that moment. I will be very grateful if you guys could test using latest rlwrap as well. My OCaml version is 4.04, I will also test against v4.02 and v4.03 just to see the difference. See you.

**Comment by marcoonroad** [comment]
"WE ARE HERE" is printed for every --no-wrapper. The new-line space was just to delimit the Sys.argv iteration.

**Comment by andrejbauer** [comment]
Oh my god! There is `wrapper` in `eff.ml` and there is `Config.wrapper`. We are using `wrapper` in `Arg.parse` and then `Config.wrapper` in `main`. How could this ever have worked?

The bug was introduced in f988cdacd1f2f3296c1e4a5da306d658e781106e by @matijapretnar.

The only change needed is that we delete `wrapper` in `eff.ml` and replace it throughout with `Config.wrapper`. Will you change your PR, or should I do it?

**Comment by marcoonroad** [comment]
eff-no-wrapper-working
eff-no-wrapper-working-diff

Alright, it indeed works. Thank you. :+1:

**Comment by marcoonroad** [comment]
Wait a minute, I will soon change the code on my Pull Request. :)

**Comment by marcoonroad** [comment]
I have discarded the `if` statement and the only change there is on the wrapper variable. Now it runs fine on my machine. Thank you.

**Comment by andrejbauer** [comment]
We should thank you for pointing out the bug!

**Comment by matijapretnar** [comment]
Yes, thank you for finding the bug! And sorry for causing it 😊

**Pull request closed without merging**
